service: ticker

frameworkVersion: ">=1.1.0"

custom:
  bucket: api.stellarterm.com
  filename: v1/ticker.json

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  ticker:
    handler: handler.ticker
    environment:
      BUCKET: ${self:custom.bucket}
      FILENAME: ${self:custom.filename}
  cron:
    handler: handler.ticker
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
    environment:
      BUCKET: ${self:custom.bucket}
      FILENAME: ${self:custom.filename}
